-- CREATE DATABASE AND TABLE
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states(
id INT AUTO_INCREMENT UNIQUE,
name VARCHAR(256),
ADD CONSTRAINT states(id) PRIMARY_KEY(id)
);
